### ISSUE TITLE
`AppImage` does not start, misses dependency

### ISSUE THREAD

**Issue by loveencounterflow** [FractalHQ/sveltekit-electron#12]
I wanted to create an `AppImage` from `sveltekit-electron`. Since I'm on Linux Mint, I changed the 

In `package.json`, I changed the `build:electron` script entry:

```json
"build:electron": "electron-builder -l --config build.config.json",
```

In `build.config.json`, I added

```json
  "linux": {
      "target": "AppImage"
    },
```

After running `pnpm run build`, there's an `*.AppImage` file in `dist`. When trying to run that file, an error is printed:

```
$ dist/Svelte\ Electron-0.0.1.AppImage
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'jsonfile'
Require stack:
- /tmp/.mount_SvelteKlfyNf/resources/app.asar/node_modules/electron-window-state/index.js
- /tmp/.mount_SvelteKlfyNf/resources/app.asar/src/electron.cjs
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/tmp/.mount_SvelteKlfyNf/resources/app.asar/node_modules/electron-window-state/index.js:5:18)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
```

From there on, the process hangs without opening a window. Because it hangs, I was able to inspect the temporary directory and could confirm there is no module `jsonfile` to be found. I did unpack the `resources/app.asar` archive as well. In the unpacked `*.asar`, in file `node_modules/electron-window-state/package.json` there's a dependency `"jsonfile": "^4.0.0"` so one should think the builder should pick this up.

**Comment by FractalHQ** [comment]
Hmmm... this seems like it could be an issue with electron-packager.  There's a lot of noise about similar issues: https://github.com/electron/electron-packager/issues/217

Have you made any progress so far?  It might be worth asking about it over there.

Did you try adding `jsonfile` to your top levels `deps` or `devDeps`?

**Comment by FractalHQ** [comment]
If there is anyone with a Linux machine who can help out with this, it would be much appreciated!

**Comment by ghostdevv** [comment]
Makes sense!

**Comment by Naratna** [comment]
I was able to successfully build the `AppImage` with `pnpm` by adding `public-hoist-pattern=*` to `.npmrc`, as pointed out in [this issue](https://github.com/electron-userland/electron-builder/issues/6289#issuecomment-1042620422)
