### ISSUE TITLE
Cannot find module 'dmg-license'

### ISSUE THREAD

**Issue by paolodina** [FractalHQ/sveltekit-electron#14]
The command `npm run build` fails with

> Cannot find module 'dmg-license'

This is because I'm on Linux and `build:electron` in `package.json` builds for mac, windows and linux by default (`-mwl`):

```
"build:electron": "electron-builder -mwl --config build.config.json",
```
[It seems](https://github.com/electron-userland/electron-builder/issues/6489#issuecomment-998559003) that electron-buider > 20.39.0 introduced this dependency.

It should be handled.

---

Btw, removing the `m` I get another error saying that I should install wine for windows builds.

I don't know how electron builder configuration works (maybe what I'd like to do it's already possible tweaking `build.config.json`) , but I'd like to be able to specify the platform(s). It could be done with:
```
"build:electron": "electron-builder $TARGET_PLATFORM --config build.config.json",
```
and invoking `npm run build` prefixed by<sup>*</sup> `TARGET_PLATFORM=-w` (windows), `TARGET_PLATFORM=-l` (linux), `TARGET_PLATFORM=-w` or any valid combination (`TARGET_PLATFORM=-ml`, etc). Example:

```
TARGET_PLATFORM="-wl" npm run build
```
(*) not sure if setting env variables via command line this way works on windows too.

In case you like the approach this should be added to the docs. If instead it's supposed to manually change the script specifying the platform or something like that, it should be added to the docs as well.

**Comment by FractalHQ** [comment]
This is a great point.  Personally, I think it would be best to leave a note in the README about changing the target platform in the build script.

**Comment by ghostdevv** [comment]
Just note that adding the environment variable before the command won't work on windows
