### ISSUE TITLE
config.kit.ssr no more supported

### ISSUE THREAD

**Issue by paolodina** [FractalHQ/sveltekit-electron#15]
SSR should be disabled via hooks `handle` function.

```
export async function handle({ request, resolve }) {
    const response = await resolve(request, {
        ssr: false
    });

    return response;
}
```

https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next222

**Comment by malhashemi** [comment]
@FractalHQ I believe this one is closed in #16
