### ISSUE TITLE
Example app fails to load in browser because `window.api` is `undefined`

### ISSUE THREAD

**Issue by oscarhermoso** [FractalHQ/sveltekit-electron#23]
## Expected:

Following the set-up instructions, the demo app should run in both Electron and the browser.

## Actual:

Page loads fine in Electron, but errors in Firefox with `Uncaught (in promise) TypeError: window.api is undefined`.

There is also a preceding error from SvelteKit `[HMR][Svelte] Unrecoverable HMR error in <Index>: next update will trigger a full reload`.

Produced error in both Chromium, Firefox on Linux (Pop!_OS 21.10).

## Problem code?

This looks like where the error is coming from, I would raise a PR but I'm unfamiliar with both SvelteKit and Electron. Hopefully the below investigation helps.

```ts
// src/routes/index.svelte

import { browser } from '$app/env';

let desktop: string;

if (browser) {
  window.api.receive('from-main', (data: any) => {
	  desktop = `Received Message "${data}" from Electron`;
	  console.log(desktop);
  });
}
```

## Screenshots

![image](https://user-images.githubusercontent.com/23239955/161360990-457eeb91-90c2-47cb-95ba-ab3821b96009.png)

![image](https://user-images.githubusercontent.com/23239955/161361024-069833ab-b63f-4fdd-bf36-b94ae9c6e316.png)

**Comment by ghostdevv** [comment]
You can't use electron code outside electron hence why it won't work in firefox

**Comment by oscarhermoso** [comment]
> You can't use electron code outside electron hence why it won't work in firefox, you can only run it in electron unfortunately - unless you have code that only runs when used in electron

@ghostdevv - Yes, I understand this, but even if Electron is unavailable, the example app can run in the browser without crashing if we check for Electron first. I raised a PR that will hopefully address the issue (https://github.com/FractalHQ/sveltekit-electron/pull/24)
