### ISSUE TITLE
Question regarding this projects license

### ISSUE THREAD

**Issue by Brainshaker95** [FractalHQ/sveltekit-electron#31]
Since this repository does not include a license I'm not sure what my rights are when using this code as a starter template. May I kindly ask that a license will be added?  
See: https://choosealicense.com/no-permission/  

In any case, thank you for the fantastic work here 🙂

**Comment by FractalHQ** [comment]
Aw man sorry I missed that!!  I'll add an MIT asap.

**Comment by Brainshaker95** [comment]
Thank you! ♥

**Comment by FractalHQ** [comment]
Added!
