### ISSUE TITLE
Update to use svelte-kit 1.0?

### ISSUE THREAD

**Issue by mhkeller** [FractalHQ/sveltekit-electron#35]
Do you have any plans to update this now that svelte-kit is at version 1.0? I tried to update it but I'm running into a weird race condition where electron tries to load the page before the vite server has launched. I have to hit command-r. I'm not sure what would have changed to cause that or why that race condition didn't exist before since `npm run dev` launches those two processes concurrently.

**Comment by FractalHQ** [comment]
Hey!  I've updated all of the dependencies to their latest versions and the dev / build seems to be working great.  How's this run on your end?

**Comment by mhkeller** [comment]
It seems to work on my newer computer so could be something weird with my old one. But just curious, is there anything guaranteeing that the electron process loads the dev server *after* the dev server runs or do they fire up simultaneously and it is a race condition?
