### ISSUE TITLE
I think child_process dependency can be removed

### ISSUE THREAD

**Issue by johanalkstal** [FractalHQ/sveltekit-electron#8]
I noticed there's a dev dependency on `child_process`. That package has been removed from npm and is under ownership of npm security holder. It's just a README file.

Not sure what the use case is/was for the package?

**Comment by FractalHQ** [comment]
Hey @johanalkstal thanks for catching this!  An older implementation used it to bypass some issues, but it's no longer needed and should be removed. I'll do that now.  Thanks!
