### ISSUE TITLE
Add `preload.ts`

### ISSUE THREAD

**Issue by bato3** [FractalHQ/sveltekit-electron#9]
Because [`require()` isn't allowed in `render`](https://stackoverflow.com/a/59888788) context, I suggest adding the preload script. 

The procedure is not complicated for `js`, but doing it for `ts` can be problematic. (Electron require plain `js`)

**Comment by FractalHQ** [comment]
Hey @bato3 - thanks for the heads up!  If you've added this already, would you mind submitting a PR?

**Comment by bato3** [comment]
@FractalHQ I would only be able to do for `.js`. `.ts` exceeds my capabilities...

**Comment by FractalHQ** [comment]
Hopefully #21 solves this for you!
